[package]
name = "filtrum"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.12.2"
serde = { version = "1", features = ["derive"] }
thiserror = "2.0.17"

[dev-dependencies]
serde_json = "1"

[lib]
name = "filtrum"
path = "src/lib.rs"